# Generated by Django 2.2 on 2019-06-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Жанр')),
                ('cover', models.ImageField(max_length=250, upload_to='', verbose_name='Обложка')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Идентификатор изображения')),
                ('company', models.CharField(max_length=250, verbose_name='Компания')),
                ('image', models.ImageField(upload_to='media', verbose_name='Изображение')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='WorkersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50, verbose_name='Имя сотрудника')),
                ('worker_photo', models.ImageField(upload_to='media', verbose_name='Портрет сотрудника')),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=4000, verbose_name='Информация о сотруднике')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ManyToManyField(related_name='genres', to='main.Genre', verbose_name='Жанр')),
                ('worker_portfolio', models.ManyToManyField(related_name='images', to='main.Image')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='main.WorkersModel', verbose_name='Фотограф'),
        ),
        migrations.AddField(
            model_name='genre',
            name='photo_examples',
            field=models.ManyToManyField(to='main.Image', verbose_name='examples'),
        ),
    ]
