# Generated by Django 2.2 on 2019-04-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workersmodel',
            old_name='worker',
            new_name='worker_photo',
        ),
    ]
