# Generated by Django 2.2 on 2019-04-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190406_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersmodel',
            name='worker_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Worker portrait'),
        ),
        migrations.AlterField(
            model_name='workersmodel',
            name='worker_portfolio',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Worker portfolio'),
        ),
    ]
